### ISSUE TITLE
Handling of HTTP errors

### ISSUE THREAD

**Issue by phisqb** [stadt-karlsruhe/ckanext-extractor#4]
Hello and thanks for your work putting this extension together! I have CKAN running on a Windows machine but the index is not the full text index of all the assets stored in CKAN. Is redis required for the plugin to work? The celery error I get is:

[2017-04-05 11:09:18,331: INFO/MainProcess] Received task: extractor.extract[d5b7a2fb-31a5-4395-adf6-0e58c076a300]
[2017-04-05 11:09:31,660: ERROR/MainProcess] Task extractor.extract[d5b7a2fb-31a5-4395-adf6-0e58c076a300] raised unexpected: HTTPError('404 Client Error: Not Found',)
Traceback (most recent call last):
  File "C:\Users\sbarn_000\Source\Repos\ckan\ckanenv32-2.7\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "C:\Users\sbarn_000\Source\Repos\ckan\ckanenv32-2.7\lib\site-packages\celery\app\trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "c:\users\sbarn_000\source\repos\ckan\ckanenv32-2.7\src\ckanext-extractor\ckanext\extractor\tasks.py", line 63, in extract
    extracted = download_and_extract(res_dict['url'])
  File "c:\users\sbarn_000\source\repos\ckan\ckanenv32-2.7\src\ckanext-extractor\ckanext\extractor\lib.py", line 38, in download_and_extract
    r.raise_for_status()
  File "C:\Users\sbarn_000\Source\Repos\ckan\ckanenv32-2.7\lib\site-packages\requests\models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

Thank you for your help.

**Comment by torfsen** [comment]
Redis is not required for ckanext-extractor.

Regarding your error: It looks like the resource could not be found at the given URL (HTTP 404 error). There should probably be a better error handling for that, I'll look into it. Thanks for reporting the issue!

**Comment by torfsen** [comment]
Fixed in b4da928: Errors during resource download are now logged as warnings.

**Comment by torfsen** [comment]
Released in version [0.3.0](https://github.com/stadt-karlsruhe/ckanext-extractor/releases/tag/v0.3.0).
